"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from "@/components/ui/select";
import {emptyRP,type RestrictivePractice} from "@/lib/safety";
import {participantFor} from "@/lib/participants";
import {definitions,type ShiftNote} from "@/lib/shift-form";
export default function SafetyPanel({note,participant,disabled,onSave}:{note:ShiftNote|null;participant:string;disabled:boolean;onSave:(value:RestrictivePractice)=>Promise<void>}){
  const [rp,setRP]=useState<RestrictivePractice>(note?.safety?.restrictivePractice??emptyRP());
  useEffect(()=>{setRP(note?.safety?.restrictivePractice??emptyRP());},[note?.id,note?.revision]);
  const profile=participantFor(participant);const update=(key:keyof RestrictivePractice,value:string)=>setRP(old=>({...old,[key]:value}));
  const choices:Partial<Record<keyof RestrictivePractice,Record<string,string>>>={used:{not_reviewed:"Not yet reviewed",yes:"Use reported",no:"Explicitly stated: no use",unsure:"Unresolved"},category:{unsure:"Unverified",environmental:"Environmental",chemical:"Chemical",physical:"Physical",mechanical:"Mechanical",seclusion:"Seclusion"},in_behaviour_plan:{not_reviewed:"Not yet reviewed",yes:"Worker says in plan",no:"Worker says not in plan",worker_does_not_know:"Worker does not know"},given_for_behaviour:{not_reviewed:"Not yet reviewed",yes:"Given for behaviour",no:"Routine treatment",unsure:"Purpose unknown"},harm:{not_reviewed:"Not yet reviewed",yes:"Harm observed",no:"Explicitly stated: no harm",unsure:"Unresolved"}};
  const labels:Record<string,string>={used:"Reported use",what_happened:"What happened — worker's own words",category:"Candidate category",in_behaviour_plan:"Worker's knowledge of the plan",schedule_item:"Schedule item",start_time:"Start time · Melbourne",end_time:"End time · Melbourne",behaviour_of_concern:"What was happening before the practice",dose_mg:"Actual dose (mg)",uses_in_24h:"Uses in the previous 24 hours",given_for_behaviour:"Medication purpose",harm:"Observed harm"};
  return <section className="safety-section">
    {profile&&<details className="profile-summary"><summary>{profile.name} · Fictional profile {profile.id}</summary><p>{profile.setting} · {profile.communication}</p><p><strong>Recorded background:</strong> {profile.conditions.join("; ")}</p><p><strong>Known risks:</strong> {profile.risks.join("; ")}</p><p><strong>Mealtime plan:</strong> {profile.mealtimePlan}</p><p><strong>Medication:</strong> {profile.medications.map(m=>m.description).join("; ")||"None behaviour-related recorded"}</p><p><strong>Goals:</strong> {profile.goals.join("; ")}</p>{profile.plan.map(item=><p key={item.id}><strong>{item.id}:</strong> {item.description}{item.maxMinutes!==undefined?` · Max ${item.maxMinutes*60} seconds`:""}{item.maxDoseMg!==undefined?` · Max ${item.maxDoseMg} mg`:""}{item.maxUses24h!==undefined?` · Max ${item.maxUses24h} use per 24 h`:""} · Recorded VIC authorisation: {item.authorised?"yes":"unverified"}</p>)}<p className="section-help">Demo profiles and question bank; clinical sign-off is required before real use. Birth dates are not supplied.</p></details>}
    {!!note?.riskFlags?.length&&<div className="risk-banner" role="status"><h3>Supervisor review items</h3>{note.riskFlags.map(flag=><p key={flag.id??flag.code}><strong>{flag.code.replaceAll("_"," ")}</strong> — {flag.reason}{flag.planItem?` · Plan reference ${flag.planItem}`:""}</p>)}<small>Urgent items are in the demo management inbox now. No external notification has been sent. Original flags remain when facts are corrected or disputed.</small></div>}
    <details><summary>Evidence states · {note?.clarificationCount??0} clarifying questions recorded</summary><div className="evidence-grid">{definitions.map(field=><div key={field.key}><span>{field.label}</span><strong>{(note?.safety?.fieldStates[field.key]??"not_reviewed").replaceAll("_"," ")}</strong></div>)}</div></details>
    <h3>Restrictive practice</h3><p className="section-help">Record observable facts. Candidate classification and plan checks are for supervisor assessment.</p>
    <div className="rp-grid">{(Object.keys(labels) as (keyof RestrictivePractice)[]).filter(key=>rp.used==="yes"||rp.used==="unsure"||key==="used").map(key=><div className="field-wrap" key={key}><label htmlFor={`rp-${key}`}>{labels[key]}</label>{choices[key]?<Select value={String(rp[key])} onValueChange={value=>update(key,value)} disabled={disabled}><SelectTrigger id={`rp-${key}`} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(choices[key]!).map(([value,label])=><SelectItem value={value} key={value}>{label}</SelectItem>)}</SelectContent></Select>:key==="what_happened"||key==="behaviour_of_concern"?<Textarea id={`rp-${key}`} value={String(rp[key])} disabled={disabled} onChange={e=>update(key,e.target.value)}/>:<Input id={`rp-${key}`} type={key.endsWith("_time")?"datetime-local":"text"} value={String(rp[key])} disabled={disabled} onChange={e=>update(key,e.target.value)}/>}</div>)}</div>
    {note?.safety?.restrictivePractice.duration_minutes!==null&&note?.safety?.restrictivePractice.duration_minutes!==undefined&&<p>Derived duration: {note.safety.restrictivePractice.duration_minutes} minutes</p>}
    {note?.status!=="complete"&&<Button variant="outline" disabled={disabled||!profile} onClick={()=>void onSave(rp)}>Save practice details</Button>}
  </section>;
}
